apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    application: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ${APPLICATION_NAME}:latest
  source:
    contextDir: ${CONTEXT_DIR}
    git:
      ref: ${SOURCE_REPOSITORY_REF}
      uri: ${SOURCE_REPOSITORY_URL}
    type: Git
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: jboss-webserver30-tomcat8-openshift:1.2
        namespace: ${IMAGE_STREAM_NAMESPACE}
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange